### ISSUE TITLE
too many fortnite builds

### ISSUE THREAD

**Issue by theboomingbomber** [FiredAnt8442448/Fortnite-Builds#1]
no fortnite builds

**Comment by theboomingbomber** [comment]
![download](https://github.com/FiredAnt8442448/Fortnite-Builds/assets/118398667/8a9935c1-1723-4a29-9900-c93b7646bacd)

**Comment by FiredAnt8442448** [comment]
hut up only send issue if u have an issue

**Comment by FiredAnt8442448** [comment]
harhar

**Comment by theboomingbomber** [comment]
![OIP](https://github.com/FiredAnt8442448/Fortnite-Builds/assets/118398667/50c2bf72-0cb2-4180-b4a6-f9deaed13a29)
now I hav fut lettuc becuasde you didnt have fotnite builds

**Comment by FiredAnt8442448** [comment]
fREAK YOU!1!111!!!!!

**Comment by FiredAnt8442448** [comment]
bye bye 🤫

**Comment by theboomingbomber** [comment]
> fREAK YOU!1!111!!!!!

hey thats mean :(((((

**Comment by theboomingbomber** [comment]
Not enough fortnite builds

**Comment by FiredAnt8442448** [comment]
wayyyyyyy too many

**Comment by theboomingbomber** [comment]
nuh uh
